name: Publish Release

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  build_and_publish:
    name: Build, Release, and Publish
    runs-on: ubuntu-latest
    outputs:
      hashes: ${{ steps.hash.outputs.hashes }}
    permissions:
      id-token: write # Required for PyPI OIDC and SLSA provenance
      contents: write # Required to create a GitHub Release

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Python
        uses: actions/setup-python@v6.3.0
        with:
          python-version: '3.12'

      - name: Install build tools
        run: pip install build

      - name: Build sdist and wheel
        run: python -m build

      - name: Generate hashes for SLSA
        id: hash
        run: |
          cd dist && echo "hashes=$(sha256sum * | base64 -w0)" >> "$GITHUB_OUTPUT"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            dist/*.tar.gz
            dist/*.whl
          generate_release_notes: true

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

  provenance:
    needs: [build_and_publish]
    permissions:
      actions: read
      id-token: write
      contents: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v2.0.0
    with:
      base64-subjects: "${{ needs.build_and_publish.outputs.hashes }}"
      upload-assets: true
